name: React build

on:
    push:
        branches: [master, frontend]
    pull_request:
        branches: [master, frontend]

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./frontend

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Try Building
              run: npm run build
              env:
                  CI: ''
